version: "3"
services:

  server:
    image: tg_bot_server
    container_name: tg_bot_server
    depends_on:
      - db
    expose:
      - "4000"
    ports:
      - "4000:4000"
    environment:
      - PG_DSN=postgres://postgres:postgres@db:54302/oauth?sslmode=disable
      - JWT_SECRET=secret!
      - SERVER_PORT=:4000
    volumes:
      - tg-bot-logs:/usr/src/app/data
    networks:
      - postgres

  db:
    image: postgres
    container_name: tg_bot_db
    expose:
      - "54302"
    ports:
      - "54302:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - tg-bot-db-data:/var/lib/postgresql/data
      - ./data/sql/:/docker-entrypoint-initdb.d/
    command: -p 54302
    networks:
      - postgres

volumes:
  tg-bot-db-data:
  tg-bot-logs:

networks:
  postgres:
    driver: bridge